wcs_hack_produit:
    resource: "@WCSHackBundle/Controller/produitController.php"
    type:     annotation

wcs_hack_commande:
    resource: "@WCSHackBundle/Controller/commandeController.php"
    type:     annotation

wcs_hack:
    resource: "@WCSHackBundle/Resources/config/routing.yml"
    prefix:   /


